# Minimal pre-commit configuration
repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: detect-private-key

  # Python linting and formatting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ['--fix']
      - id: ruff-format

  # Security checks with Bandit
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.10'
    hooks:
      - id: bandit
        args: ['-ll']  # Only report medium and high severity issues
        exclude: ^tests/

  # Markdown formatting with mdformat
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.19
    hooks:
      - id: mdformat
        args: ['--end-of-line', 'lf']  # Force LF line endings
        additional_dependencies:
          - mdformat-gfm  # GitHub Flavored Markdown support
          - mdformat-frontmatter  # YAML frontmatter support
          - mdformat-footnote  # Footnote support

# Configuration settings
default_language_version:
  python: python3
